config/routes.rb
Rails.application.routes.draw do
  # mount ActionCable.server => '/cable'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  namespace :api do
    post :upload_image, to: 'utils#upload_image'

    resources :users, only: [] do
      member do
        post :subscribe
      end
    end

    resources :posts do
      member do
        post :like
      end
      resources :comments do
        member do
          post :comlike
        end
      end
    end
  end
  resources :groups

  resources :posts do
    resources :comments , only:[:create]
  end

  resources :users do
    resources :messages , only:[:new, :show, :index, :create]
  end

  

  get '@:username/:post_id', to: 'pages#show', as: 'post_page'
  get '@:username', to: 'pages#user', as: 'user_page'
  get ':group', to: 'groups#show', as: 'group_page'
  root 'pages#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/frontend/_comment.html.erb
<div class="card-content">
  <header class="card-header">
    <%= image_tag comment.user.avatar.variant(resize: "50X50!") if comment.user.avatar.attached? %>
    <p class="card-header-title">
      <%= comment.user.username %>
    </p>
  </header>
  <div class="card-content">
    <div class="content">  
      <%= simple_format(comment.content) %>
    </div>
  </div>
  <footer class="card-footer">
    <%= link_to "#", id: "", class: "has-text-danger", data: { post:comment.post_id, slug: comment.id }, "@click": "addComLike" do %>
      <% if user_signed_in? && current_user.comlike?(comment) %>
        <i class="fas fa-heart like<%= comment.id%>" ></i>
      <% else %>
        <i class="far fa-heart like<%= comment.id%>" ></i>
      <% end %>
      <span class="recomlikes like<%= comment.id%> has-text-dark">
        <%= Commentlike.where( :comliked => comment).count %>
      </span>
    <% end %>
  </footer>
</div>

app/views/shared/frontend/_comment_area.html.erb
<% if user_signed_in? %>
  <%= form_with model: comment, url: post_comments_path(post), class: 'comment_form', remote: true do |form| %>
    <%= form.text_area :content, rows: 2, class: "textarea is-small" %>
    <%= form.button '送出', class: "button is-dark" %>
  <% end %>
<% end %>

app/views/shared/frontend/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/" >
      <h1 class="is-size-3">Hello</h1>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if user_signed_in? %>
            <%= link_to user_messages_path(current_user), class:"navbar-item" do %>
              <i class="far fa-envelope"></i>
            <% end %>
            <%= link_to new_post_path, class:"navbar-item" do %>
              <i class="fas fa-edit"></i>
            <% end %>
            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link">
                <%= avatar(current_user, size: 50) %>
                <%= current_user.username %>
              </a>
              <div class="navbar-dropdown">
                <%= link_to "個人資料", edit_user_registration_path, class: 'navbar-item' %>
                <hr class="navbar-divider">
                <%= link_to "我的貼文", posts_path, class: 'navbar-item' %>
                <hr class="navbar-divider">
                <%= link_to "登出", destroy_user_session_path, method: :delete, class: 'navbar-item' %>
              </div>
            </div>
          <% else %>
            <%= link_to "註冊", new_user_registration_path, class: 'button is-primary' %>
            <%= link_to "登入", new_user_session_path, class: 'button is-light' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>