config/routes.rb
Rails.application.routes.draw do
  # mount ActionCable.server => '/cable'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  namespace :api do
    post :upload_image, to: 'utils#upload_image'

    resources :users, only: [] do
      member do
        post :subscribe
      end
    end

    resources :posts do
      member do
        post :like
      end
      resources :comments do
        member do
          post :comlike
        end
      end
    end
  end
  resources :groups

  resources :posts do
    resources :comments , only:[:create]
  end

  resources :users do
    resources :messages , only:[:new, :show, :index, :create]
  end

  

  get '@:username/:post_id', to: 'pages#show', as: 'post_page'
  get '@:username', to: 'pages#user', as: 'user_page'
  get ':group', to: 'groups#show', as: 'group_page'
  root 'pages#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flash.html.erb
<div class="notification is-primary">
  <button class="delete"></button>
  <%= notice %>
</div>

app/views/shared/_leftmenu.html.erb
<aside class="menu">
  <p class="menu-label title is-6">
    群組
  </p>
  <ul class="menu-list">  
  <% @groups.each do |group| %>
    <%= link_to group_page_path(group.name), class: 'has-text-dark title is-4' do %>  
      <li><%= group.name %></li>
    <% end %>
  <% end %>
  </ul>
</aside>

app/views/shared/_message_area.html.erb
<%= form_with model: message, url: user_messages_path(user), class: 'message_form', remote: true do |form| %>
  <p>to : <%= user.username %></p>
  <%= form.text_field :foruser, value: user.id , type: "hidden"%>
  <%= form.text_field :talkroom, value: talkroom , type: "hidden"%>
  <div class="field">
    <% form.label :content %>
    <%= form.text_area :content, rows: 3, class: 'textarea is-primary is-medium ' %>
  </div>
  <%= form.button '送出', class: "button is-dark navbar-end" %>
<% end %>

app/views/shared/_messagemenu.html.erb
<aside class="menu">
  <p class="menu-label title is-6">
    訊息
  </p>
  <% users.each do |user| %>
    <%= link_to user_message_path(current_user, user.user), class: 'has-text-dark title is-4' do %> 
    <ul class="menu-list">
      <li class="pagination-list">
      <%= avatar(user.user, size: 50) %>
      <p class="title is-6"><%= user.user.username %></p>
      </li>
    </ul>
    <% end %>
  <% end %>
</aside>

app/views/shared/_post.html.erb
<%= link_to post_page_path(post.user.username, post), class: 'has-text-dark' do %>
  <div class="box is-size-5" style="height: 230px;">
    <article class="media">
      <div class="media-left">
        <figure class="image is-64x64">
          <%= image_tag post.cover_image if post.cover_image.attached? %>
        </figure>
      </div>
      <div class="media-content">
        <div class="content">
          <p>
            <strong><%= post.title %></strong> <small><%= post.user.username %></small> <small><%= time_ago_in_words(post.created_at) %></small>
            <br>
            <%= strip_tags(post.content).truncate(100) %>
          </p>
        </div>
        <nav class="level is-mobile">
          <div class="level-left">
            <div class="level-item">
              <i class="far fa-comment-dots"></i>
              <span class=""><%=Comment.where( :post_id => post).count %></span>
            </div>
            <div class="level-item">
              <i class="fas fa-heart has-text-danger"></i>
              <span class=""><%= Like.where( :liked => post).count %></span>
            </div>
          </div>
        </nav>
      </div>
    </article>
  </div>
<% end %>