config/routes.rb
Rails.application.routes.draw do
  # mount ActionCable.server => '/cable'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  namespace :api do
    post :upload_image, to: 'utils#upload_image'

    resources :users, only: [] do
      member do
        post :subscribe
      end
    end

    resources :posts do
      member do
        post :like
      end
      resources :comments do
        member do
          post :comlike
        end
      end
    end
  end
  resources :groups

  resources :posts do
    resources :comments , only:[:create]
  end

  resources :users do
    resources :messages , only:[:new, :show, :index, :create]
  end

  

  get '@:username/:post_id', to: 'pages#show', as: 'post_page'
  get '@:username', to: 'pages#user', as: 'user_page'
  get ':group', to: 'groups#show', as: 'group_page'
  root 'pages#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/home.html.erb
<section class="p-6">
  <h1 class="font-thin text-3xl">Hello, Yu :)</h1>
</section>

app/views/pages/index.html.erb
<section class="container">
  <div class="columns">
    <div class="column is-2">
      <%= render 'shared/leftmenu' %>
    </div>
    <div class="column is-7">
      <%= render partial:'shared/post' , collection: @posts %>
    </div>
  </div>
</section>

app/views/pages/show.html.erb
<section class="container">
  <div class="columns">
    <div class="column is-2">
      <%= render 'shared/leftmenu' %>
    </div>
    <div class="column is-8">
      <div class="card">
        <% if @post.cover_image.attached? %>
        <div class="card-image">    
          <%= image_tag @post.cover_image %>
        </div>
        <% end %>
        <div class="card-content">
          <div class="media">
            <div class="media-left">
              <figure class="image is-48x48">
                <%= image_tag @post.user.avatar.variant(resize: "50X50!") if @post.user.avatar.attached? %>
              </figure>
            </div>
            <div class="media-content">
              <p class="title is-4"><%= @post.title %></p>
              <div class="subtitle is-6">
              <%= link_to user_page_path(), class: "user has-text-dark" do%>
                <span>@<%= @post.user.username %></span>
              <% end %>
              <% unless current_user == @post.user %>
              <%= link_to "#", id: "subscribe", class: "subscribe has-text-link", data: { user: @post.user.id }, "@click": "addSubscribe" do %>
                <% if user_signed_in? && current_user.subscribe?(@post.user) %>
                  <i class="fas fa-bell subscribe"></i>
                <% else %>
                  <i class="far fa-bell subscribe"></i>
                <% end %>
              <% end %>
              <% end %>
              </div>
            </div>
          </div>
          <div class="content">
            <p class="txet-center"><%= @post.content.html_safe %></p>
          </div>
          <footer data-controller="post">
          <%= link_to "#", id: "like", class: "like has-text-danger", data: { slug: @post.slug }, "@click": "addLike" do %>
            <% if user_signed_in? && current_user.like?(@post) %>
              <i v-bind:class="iconrelike"></i>
            <% else %>
              <i v-bind:class="iconlike"></i>
            <% end %>
            <span class="relikes has-text-dark">
              <%= @relikes %>
            </span>
          <% end %>
          </footer>
          
          <footer class="card-footer">
            <p class="card-footer-item">留言</p>   
          </footer>
          <footer>
            <%= render 'shared/frontend/comment_area', post: @post, comment: @comment %>
          </footer>
        </div>
      </div>
      <div class="comment-list comlike">
        <%= render partial: 'shared/frontend/comment', collection: @comments %>
      </div>
    </div>
  </div>
</section>

app/views/pages/user.html.erb
<section class="container">
  <div class="column">
    <div class="box">
      <article class="media">
        <div class="media-left">
          <figure class="image is-64x64">
            <%= image_tag @user.avatar.variant(resize: "50X50!") if @user.avatar.attached? %>
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <p>
              <strong><%= @user.username %></strong>
              <% unless current_user==@user %>
              <%= link_to "#", id: "subscribe", class: "subscribe has-text-link", data: { user: @user.id }, "@click": "addSubscribe" do %>
                <% if user_signed_in? && current_user.subscribe?(@user) %>
                  <i class="fas fa-bell subscribe"></i>
                <% else %>
                  <i class="far fa-bell subscribe"></i>
                <% end %>
              <% end %>
              <%= link_to new_user_message_path(@user), id: "message", class: "message has-text-info" do %>
                <i class="far fa-envelope"></i>
              <% end %>
              <% end %>
              <br>
              個人簡介:
            </p>
            <p><%= @user.intro %></p>
          </div>
        </div>
      </article>
    </div>
  </div>
  <div class = "column">
    <p class = "title is-4">貼文:</p>
    <%= render partial:'shared/post', collection: @userposts %>
  </div>
</section>